-- ============================================================
-- V1: Create iamdb schema and all IAM tables
-- Canonical DDL from db-structure.md § 4
-- DO NOT edit this file after it has been applied to any environment.
-- Create a new V2 migration for any schema changes.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS iam;

-- ============================================================
-- TENANTS — root of the multi-tenant model
-- ============================================================
CREATE TABLE iam.tenants (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    domain      VARCHAR(255) UNIQUE,
    plan        VARCHAR(30) NOT NULL DEFAULT 'STANDARD'
                CHECK (plan IN ('TRIAL','STANDARD','ENTERPRISE')),
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE','SUSPENDED','TRIAL','CANCELLED')),
    settings    JSONB NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE iam.users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES iam.tenants(id),
    username        VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    avatar_url      TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE','INACTIVE','LOCKED','PENDING')),
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID,
    version         BIGINT NOT NULL DEFAULT 0,
    UNIQUE(tenant_id, username),
    UNIQUE(tenant_id, email)
);

-- ============================================================
-- ROLES
-- ============================================================
CREATE TABLE iam.roles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES iam.tenants(id),
    name            VARCHAR(100) NOT NULL,
    code            VARCHAR(50) NOT NULL,
    description     TEXT,
    is_system_role  BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, code)
);

-- ============================================================
-- PERMISSIONS
-- ============================================================
CREATE TABLE iam.permissions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resource    VARCHAR(100) NOT NULL,
    action      VARCHAR(50) NOT NULL,
    scope       VARCHAR(50),
    description TEXT,
    UNIQUE(resource, action, scope)
);

-- ============================================================
-- ROLE-PERMISSION JUNCTION
-- ============================================================
CREATE TABLE iam.role_permissions (
    role_id         UUID NOT NULL REFERENCES iam.roles(id) ON DELETE CASCADE,
    permission_id   UUID NOT NULL REFERENCES iam.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- ============================================================
-- USER-ROLE JUNCTION
-- ============================================================
CREATE TABLE iam.user_roles (
    user_id         UUID NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    role_id         UUID NOT NULL REFERENCES iam.roles(id) ON DELETE CASCADE,
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    granted_by      UUID,
    expires_at      TIMESTAMPTZ,
    PRIMARY KEY (user_id, role_id)
);

-- ============================================================
-- API KEYS
-- ============================================================
CREATE TABLE iam.api_keys (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES iam.tenants(id),
    name            VARCHAR(100) NOT NULL,
    key_hash        VARCHAR(255) NOT NULL UNIQUE,
    prefix          VARCHAR(10) NOT NULL,
    scopes          TEXT[] NOT NULL DEFAULT '{}',
    rate_limit_rpm  INT NOT NULL DEFAULT 60,
    last_used_at    TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ,
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID
);

-- ============================================================
-- REFRESH TOKENS
-- ============================================================
CREATE TABLE iam.refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    issued_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at  TIMESTAMPTZ,
    ip_address  INET,
    user_agent  TEXT
);

-- ============================================================
-- OUTBOX (Debezium CDC → Kafka — Phase 2)
-- ============================================================
CREATE TABLE iam.outbox_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type  VARCHAR(100) NOT NULL,
    aggregate_id    UUID NOT NULL,
    event_type      VARCHAR(200) NOT NULL,
    payload         JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at    TIMESTAMPTZ,
    retry_count     INT NOT NULL DEFAULT 0,
    error_message   TEXT
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_iam_users_tenant     ON iam.users(tenant_id);
CREATE INDEX idx_iam_users_email      ON iam.users(tenant_id, email);
CREATE INDEX idx_iam_refresh_tokens_user ON iam.refresh_tokens(user_id);
CREATE INDEX idx_iam_refresh_tokens_hash ON iam.refresh_tokens(token_hash);
CREATE INDEX idx_iam_api_keys_tenant  ON iam.api_keys(tenant_id) WHERE is_active = true;
CREATE INDEX idx_iam_outbox_unprocessed ON iam.outbox_events(created_at) WHERE processed_at IS NULL;
