server:
  port: 8089

spring:
  application:
    name: cms-form-service
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/auth/.well-known/jwks.json

cms:
  security:
    public-paths:
      - "/actuator/**"
      - "/dev/**"
