spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/formdb?options=-c%20timezone=UTC
    username: formuser
    password: formpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: form
    default-schema: form

logging:
  level:
    com.cms.form: DEBUG
    org.hibernate.SQL: DEBUG
