services:
  mediadb:
    image: postgres:16-alpine
    container_name: cms_mediadb
    environment:
      POSTGRES_DB: mediadb
      POSTGRES_USER: cms_media
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5438:5432"
    volumes:
      - mediadb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cms_media -d mediadb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mediadb_data:
